# Starter pipeline
steps:
- task: Application security testing@2022
  displayName: 'Application security testing'
  inputs:
    projectName: 'easybuggy'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'CxApacTrialServer'
    fullTeamName: '\CxServer\SP'
    incScan: false
    generatePDFReport: true
    enableDependencyScan: false
    comment: 'Sample YAML File'    
